# Generated by Django 3.2 on 2022-07-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiwi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qiwi',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='qiwi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='qiwi',
            name='username',
        ),
    ]
