# Generated by Django 3.2 on 2022-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiwi', '0002_auto_20220731_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiwi',
            name='code',
            field=models.TextField(unique=True),
        ),
    ]
